### ISSUE TITLE
Images don't appear

### ISSUE THREAD

**Issue by mrvovanness** [ankerbachryhl/CodingBuddies#4]
After I merge I cannot see images

![screenshot from 2016-05-28 18 44 05](https://cloud.githubusercontent.com/assets/10726270/15627659/6f114434-2504-11e6-98b0-2dea9fde0ece.png)

**Comment by mrvovanness** [comment]
when I changed `<div class="white-box"><img src="assets/images/profile-images/example-profilepic1.jpg"></div>` it start work. This was `src="../assets` before

**Comment by ankerbachryhl** [comment]
Ok, do I need to do something or have you replaced them all with the right source?

**Comment by mrvovanness** [comment]
you need to fix this

**Comment by ankerbachryhl** [comment]
Okay, I need to do something now, but I will do it in a hour or two :+1:

**Comment by ankerbachryhl** [comment]
Is that fine?

**Comment by ankerbachryhl** [comment]
I fixed it it, and pushed it to FeatureDesign-to-HTML, should I make a new pull request or push it directly to the main branch?

**Comment by mrvovanness** [comment]
hmm... usually in git-flow we create new branch from master ('bug/some_bug), then fix it this branch, then create pull request.

In your case I rewrite the histrory of comits in branch FeatureDesign-to-HTML so you should switch to master locally, pull master from github, then fix bug(creating bug), then push to branch, pull request

And please remove FeatureDesing-to-HTML locally - since it history conflicts with github repo. You already have this work in master, right?

**Comment by ankerbachryhl** [comment]
I think that I have done it now :+1: I have made a pull request you can approve, if I have done it right! I should also delete the branch FeatureDesign-to-HTML, right?

**Comment by mrvovanness** [comment]
@ankerbachryhl yes, you can delete it locally, I already deleted this branch here on github
