### ISSUE TITLE
Weird structure of dom tree

### ISSUE THREAD

**Issue by mrvovanness** [ankerbachryhl/CodingBuddies#6]
@ankerbachryhl  take a look please, it seems there is a mistake in html structure, `link`, `tilte` tags

![screenshot from 2016-05-29 02 52 45](https://cloud.githubusercontent.com/assets/10726270/15630187/b063f438-2548-11e6-8c89-a48f149fa07a.png)

**Comment by ankerbachryhl** [comment]
Ahh it is because I'm using jade, where you can include other .jade files like: 

`include ./recommended.jade`

Does it make any bugs or proplems, because if it does I can change it :+1:

**Comment by mrvovanness** [comment]
@ankerbachryhl  It does not make any bug but this make html not appropriate, so I'll leave it open, so we don't forget about it

**Comment by ankerbachryhl** [comment]
@uniforlyff Have solved this proplem :+1: Can I close the issue? :)

**Comment by mrvovanness** [comment]
Yes!
